language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
    - pipenv install --dev
    - pipenv install coveralls

before_script:
    - pipenv run flake8 --ignore=E501 simple_model

script:
    - pipenv run py.test --cov=redis_hash --cov-report=term-missing

after_script:
    - pipenv run coveralls
